name: Automated Unit Tests

on:
  - push

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
